### PR TITLE
Customizable Helmfile Locations

### PR DESCRIPTION
**Pull request by Benbentwo**
## what
* Replace hardcoded file location with input vars

## why
* Allows customization of helmfiles

### CODE REVIEW

**Comment by milldr** [comment]
we can already set the helmfile path with a combination of the args `helmfile` and `helmfile_path`

**Review by milldr — CHANGES_REQUESTED** [review]
see comment

**Comment by goruha** [comment]
@milldr we support custom paths for helmfiles
https://github.com/cloudposse/github-action-deploy-helmfile/blob/Customizable-paths/root/deploy/helmfile.yaml#L13

the case why it works that way is a convention to inject `platform` settings from the chamber
https://github.com/cloudposse/github-action-deploy-helmfile/blob/Customizable-paths/entrypoint.sh#L16

https://github.com/cloudposse/github-action-deploy-helmfile/blob/Customizable-paths/root/deploy/helmfile.yaml#L15

What is the bug you get with the current strategy?

**Review by goruha — CHANGES_REQUESTED** [review]
see comment https://github.com/cloudposse/github-action-deploy-helmfile/pull/11#issuecomment-1303271098

**Pull request closed without merging**
